### ISSUE TITLE
v1.6.3 not tagged

### ISSUE THREAD

**Issue by sjamaan** [jpellegrini/pll#1]
Hi there,

This egg's release-info file contains a reference to a "1.6.3" release, but there's no corresponding tag, so the URL `https://github.com/jpellegrini/pll/tarball/v1.6.3` returns a 404 not found. Could you please push the tag, or else remove the release from the release-info file?

Thanks!

**Comment by jpellegrini** [comment]
Thank you for reporting this!
I have pushed the 1.6.3 tag.
